/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '9/19/16 11:38 PM' with Gradle 2.14
 *
 * @author sqlin, @date 9/19/16 11:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
